### ISSUE TITLE
How to clear image cache

### ISSUE THREAD

**Issue by Gob-Lin** [jinSasaki/Vulcan#20]
How can I clear the image cache?

Vulcan.defaultImageDownloader.cache?.removeAll()

doesn't seem to work.

Thank you,

P

**Comment by jinSasaki** [comment]
@HeliosDev

It seems that the code is working as expected.
I confirmed that [`NSCache#removeAllObjects`](https://github.com/jinSasaki/Vulcan/blob/master/Sources/Vulcan/ImageDownloader.swift#L83) is running when I tap the "Cache clear" button of the sample application.
Please tell me why you thought that it was not working.

Thank you.

**Comment by Gob-Lin** [comment]
Here is what I get when I try 

Vulcan.defaultImageDownloader.cache?.removeAll()

![schermata 2017-04-30 alle 20 35 13](https://cloud.githubusercontent.com/assets/3015630/25566994/91ee10a6-2de4-11e7-9f4f-0c3b26f10ebe.png)

**Comment by jinSasaki** [comment]
@HeliosDev 

The README has usage of version 0.3.0.

You use CocoaPods?
I released 0.3.0 to CocoaPods right now.
Please try `$ pod update Vulcan`. :)

**Comment by Gob-Lin** [comment]
removeAll() doesn't generate errors anymore, thanks.
However there is another problem: on the view controller where I call removeAll(), now when I load the images, they show for a brief moment then they disappear :-(

**Comment by HeliosDev** [comment]
Any idea about it?

**Comment by Gob-Lin** [comment]
Please ignore my previous remark, it was a bug in my code.
Great library, thanks.

**Comment by jinSasaki** [comment]
Thanks for your question :)
